### ISSUE TITLE
time_zone_info.cc: declaration shadows a local variable (zip)

### ISSUE THREAD

**Issue by aswna** [google/cctz#117]
Hi guys,
might this worth to clean it up?

    src/time_zone_info.cc:506:40: error: declaration shadows a local variable [-Werror,-Wshadow-uncaptured-local]
    auto get_char = [](ZoneInfoSource* zip) -> int {
                                       ^
    ...
    src/time_zone_info.cc:391:66: note: previous declaration is here
    bool TimeZoneInfo::Load(const std::string& name, ZoneInfoSource* zip) {
                                                                     ^

**Comment by devbww** [comment]
My opinion is no.  As the flag says, the local is uncaptured so the lambda argument isn't actually shadowing anything.  And if get_char() was an actual function, instead of a lambda, no one would think twice about reusing the name.  I also thought it was a feature that the local and the parameter had the same name, given that they refer to the same thing.

However, I gave up on trying to fight these questionable warnings long ago, so sure ... I'll send a PR.  Thanks.
