### ISSUE TITLE
Help with underflows on Fuchsia

### ISSUE THREAD

**Issue by kpozin** [google/cctz#187]
I'm trying to get cctz's tests passing on Fuchsia, currently targeting x64 (arm64 is next).

The last part of `MakeTime.SysSecondsLimits` in `time_zone_lookup_test.cc` is failing:
```text
Expected equality of these values:
  "-2147481748-01-01T00:00:00+00:00"
  format(RFC3339, tp, utc)
    Which is: "-9223372036854775808-01-01T00:00:00+00:00"
```

Setting a year of `-2147481748` apparently causes an underflow. Where in the cctz library (or somewhere else?) should I be looking to fix this behavior?

Thanks!

**Comment by devbww** [comment]
It looks like the expectation you are referring to is ...
```
EXPECT_EQ("-2147481748-01-01T00:00:00+00:00", format(RFC3339, tp, cut));
```
around line 1025.  If so, my first concern is that the test has been changed because that line uses the timezone `cut`, whereas your output says `utc`.

That said, that part of the test is about conversions in the **libc:UTC** timezone, which means it mostly concerns the behavior of `gmtime_r(3)` from your C library.

It is difficult to say more without being about to run the code, but my first question would be _"how does `gmtime_t()` behave on a `time_t` value of -67768040609740800?"_  My guess is that it fails.  It should return `{-2147483648, 0, 1, 0, 0, 0}`.

**Comment by devbww** [comment]
Did you discover anything about the behavior of your `gmtime_t()`, or is this no longer an issue?

**Comment by kpozin** [comment]
I apologize for not getting back to this earlier.

Fuchsia uses musl for Posix-related libraries:
* [gmtime_r.c](https://cs.opensource.google/fuchsia/fuchsia/+/master:zircon/third_party/ulib/musl/src/time/gmtime_r.c)
* [__secs_to_tm.c](https://cs.opensource.google/fuchsia/fuchsia/+/master:zircon/third_party/ulib/musl/src/time/__secs_to_tm.c)

`gmtime_r()` for `-67768040609740800` does indeed fail; it yields a `tm` with all fields set to 0.

These are the two underflow conditions in `__secs_to_tm`:
```cpp
  if (t < INT_MIN * 31622400LL || t > INT_MAX * 31622400LL)
    return -1;
```
```
  if (years + 100 > INT_MAX || years + 100 < INT_MIN)
    return -1;
```
The second is the one that's triggered, with an off-by-one error. (The year ends up being  `-2147483649`.)

It appears there's a patch attempting to fix this that was never merged: https://www.openwall.com/lists/musl/2016/11/02/1
However, the patch is incomplete, because with it, the month ends up off by 2:
```
{0, 0, 0, 1, 2, -2147483648}
```
