### ISSUE TITLE
Get rid of global lock time_zone_impl.cc#L64

### ISSUE THREAD

**Issue by Tagar** [google/cctz#23]
It would be great to get rid of global lock at https://github.com/google/cctz/blob/master/src/time_zone_impl.cc#L64
as described in comments  
https://issues.cloudera.org/browse/IMPALA-3316?focusedCommentId=206859&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-206859

**Comment by devbww** [comment]
That lock is only used when initially loading the zoneinfo data for a named zone.  It is not taken when doing any conversions using a loaded zone.  Compared to actually reading the zoneinfo data, taking the lock is essentially free.

A lock is also taken when you try to load an already loaded zone, but only momentarily.  It will become a shared lock when we can assume C++14.

I don't think any significant overhead could be demonstrated in a realistic workload because of this.

**Comment by Tagar** [comment]
Great. Thanks Bradley.
