### ISSUE TITLE
std::chrono::high_resolution_clock::time_point

### ISSUE THREAD

**Issue by Siesh1oo** [google/cctz#27]
Is it intentional that only std::chrono::system_clock::time_point is supported by parse, format and conversion functions, but not std::chrono::high_resolution_clock::time_point?

**Comment by devjgm** [comment]
Yes, that is intentional. `std::chrono::system_clock` is the only clock defined by the C++ standard whose time points can be mapped to some notion of civil time. See http://en.cppreference.com/w/cpp/chrono/system_clock

In particular, there is no guaranteed way to map a `std::chrono::high_resolution_clock::time_point` to a year, month, and day in any meaningful way.
