### ISSUE TITLE
add microseconds support

### ISSUE THREAD

**Issue by tgy** [google/cctz#39]
I guess it's not really 'civil' to deal with microseconds but it could be interesting to add precision to the `civil_time` objects by adding a `microseconds` attribute.

**Comment by devbww** [comment]
I think we sympathize with the general idea, however, subseconds do not have the same kind of civil hierarchy as YMDhms.  For example, why did you choose microseconds?  How would we reconcile your request with someone who asked for nanoseconds?

Once you get into the subsecond realm it also seems like you are more likely talking about an absolute time_point rather than some notion of the civil time of day.

The simplest idea, then, seemed to be leaving any subsecond handling up to the user.

**Comment by tgy** [comment]
I understand this is not the purpose of the `cctz` library. That's why I decided to go for Howard Hinnant's [date](https://github.com/HowardHinnant/date) libary, with which I can deal with absolute `time_point` objects.

Thank you for your answer!

**Comment by devbww** [comment]
OK, thanks.  If you're only dealing with absolute `time_point` objects then you indeed don't need anything related to time zones ... absolute times are, by definition, time-zone independent.
