### ISSUE TITLE
Abbreviated time zones?

### ISSUE THREAD

**Issue by vspinu** [google/cctz#46]
A range of common abbreviated(?) timezones are not found on my machine (notably CET, EST). What is the recommended way to deal with those? Is there a conversion table somewhere that I can use? 

Thanks.

**Comment by devbww** [comment]
Hi.

I think the clearest answer is to ask in response what places are you thinking of when you say "CET" and "EST"?

For example, by "EST" do you mean the places that share timezone history with New York, NY USA?  If so, then the recommended zone name is "America/New_York".

**Comment by vspinu** [comment]
I know that CET/CEST, EST/EEST are not proper timezones. They are more like UTC offsets. I just wonder if there is a recommended or standard way to treat those. When  a date-time string contains EST what shall I do with it (assuming that I am constrained not to throw an error)? Simply pick a representative city and be done with it? Any suggestions where I can get a mapping like that?

**Comment by devbww** [comment]
I would say there is no recommended/standard way to map abbreviations to time zones.

You could enumerate all the abbreviations used by a time zone using a simple zoneinfo parser (which I'd be happy to assist you with).  However, even then the answer may not be unique ("EST" is itself historically ambiguous).  And the abbreviations used today might not even match those used in the past.

In short, converting a civil time and a (non-numeric) abbreviation to an absolute time is problematic.

**Comment by vspinu** [comment]
Thanks for the input. I guess I will do then something ad hoc and will place a big warning about the caveats in the docs.

**Comment by devjgm** [comment]
I agree with Brad. I'd also suggest that you may want to change your application/library to accept/produce time strings with UTC offsets rather than time-zone abbreviations. That is, prefer the %z or %Ez format specifiers. This will make formatting/parsing easy and unambiguous.

If you're unable to do that, then you might make your own little table that maps a handful of common abbreviations to the time-zone identifiers that you'll assume they mean. That won't always work, but it's unclear what else you could do if returning an error is not an option.
