### ISSUE TITLE
Make tzdir a parameter to TimeZoneInfo::Load?

### ISSUE THREAD

**Issue by hadley** [google/cctz#6]
This would be useful for R as R bundles it's own zoneinfo db on windows. I think it's a bit more elegant as an explicit parameter, rather relying on a global variable.

(But it's not clear to me how that would interact with localtime)

**Comment by devbww** [comment]
Hi Hadley,

I presume by "global variable" you are referring to the support of `${TZDIR}` to override the root of the "zoneinfo" tree, or maybe the hard-coded fallback path (`/usr/share/zoneinfo`).

I'm a little hesitant to support specifying the root on every `LoadTimeZone()` call as it is nice to know that all the tzdata comes from a consistent release.  But perhaps there could be some "initialization" step where you could set the fallback path.  Or perhaps you could just bundle the cctz source and change the compile-time default as you see fit.

Bradley

**Comment by hadley** [comment]
Right - I really dislike the use of env vars to pass important information into a function. One of the things I find particularly appealing about cctz is that you're not reliant on setting the TZ env var. I don't think it's a big issue, and I certainly could work around it when bundling.

**Comment by mj1856** [comment]
I would also appreciate this feature.  :+1:

**Comment by devbww** [comment]
For what it's worth, in commit [49657ca](https://github.com/google/cctz/commit/49657ca5dc57a343a233b2e418594e9bade1976a) I tweaked `cctz::LoadTimeZone()` to respect absolute names, so until there is a general solution you'll be able to get to the zoneinfo of your choosing using an absolute path.

**Comment by eddelbuettel** [comment]
I would like to reopen / revisit / test this.  For our purposes (and that is a royal "we" between @hadley and myself) setting [the `TZDIR` variable we need](https://github.com/google/cctz/blob/master/src/time_zone_info.cc#L518-L526) in the startup of the R package using this (eg my [RcppCCTZ package](https://github.com/eddelbuettel/rcppcctz) for R) is probably good enough. 

I am now building some infrastructure on top of this (to deal with nanoseconds from R) and having this on Windows would be good.  It already builds and compiles (as R on Windows _always_ uses a good-enough-for-this g++-4.9 version) but we will need to work out which `_MING32` / `_MINGW64` identifiers we need to put back on it, preferably without causing harm to those using the MSVC tools.

**Comment by eddelbuettel** [comment]
I had a look.  We need `strptime()`, maybe from [here / from BSD](http://stackoverflow.com/questions/321849/strptime-equivalent-on-windows).  We also need `get_tzname` and `get_timezone`.  All doable, especially in RcppCCTZ, but we need someone with more Windows skills (and interest) than me to push this forward.

**Comment by devbww** [comment]
For strptime() we currently fall back to C++11's std::get_time(), but the strptime-equivalent-on-windows question you referenced indicates that is only available on >= VS2015.  After that I have no better suggestion than the NetBSD code.  cctz::parse() does the minimal amount of work to support the extended formats, and do integer parsing quickly, but falls back to standard functions for the rest (including localization).  That seems like the best thing to do.

We're not Windows people either, so I know nothing of get_tzname() or get_timezone().  Where do you need them?

**Comment by eddelbuettel** [comment]
It is a bit a special situation. For R (which from what we're many analysts at your shop use too), builds on Windows _always_ happen with one particular g++ version via MinGW -- the so-called [Rtools](https://cran.r-project.org/bin/windows/Rtools/) provide it.  That is none of your concerns, I only stress it because it means 'Windows && ! MSVC' which is a bit of an odd beast.

The good news is that we get most of C++11. So CCTZ should fit the bill -- I do built RcppCCTZ (the R bindings of CCTZ via the Rcpp interface) as C++11.  

I mostly have Windows access when in the office so again on Monday, but I did fall pretty flat this afternoon.

**Comment by eddelbuettel** [comment]
Follow-up:  the "`strptime()` via C++11 fallback" won't work for R as it has its g++ version more-or-less hardwired to g++ 4.9.* ... which does not have `std::get_time()`.  Only g++-5 and later do.  

That's the bad news.  The good news are, inter alia,

- dropping the BSD strptime into something like `src/thirdparty/strptime.c` and including it works
- I have working `OFFSET` and `ABBR` definitions for MinGW which can send in via PR
- setting TZDIR to `${RHOME}/share/zoneinfo` works

**Comment by eddelbuettel** [comment]
Here is a minimal proof of concept:

```r
R> Sys.info()[1:3]
                     sysname                      release                      version 
                   "Windows"                      "7 x64" "build 7601, Service Pack 1" 
R> helloMoon()
New_York   Sydney 
 "-0400"  "+1000" 
R> 
```

where [`helloMoon()`](https://github.com/eddelbuettel/rcppcctz/blob/master/src/examples.cpp#L29-L48) is a very simple function following your example.

**Comment by eddelbuettel** [comment]
Dang. I had tricked myself earlier and not actually successfully included the BSD `strptime`.

**Comment by eddelbuettel** [comment]
So ... some good news and closure.  

After we realized that `strptime` was missing when g++-4.9 is used via MinGW (ie the prescribed toolchain for R on Windows), @dcdillon kindly set out to port it over from the libc++ of LLVM.  So we now have a [single file](https://github.com/eddelbuettel/rcppcctz/blob/master/inst/include/get_time.h) providing this and hooks into the CCTZ code we have in [RcppCCTZ](https://github.com/eddelbuettel/rcppcctz).

This has now arrived on [CRAN](https://cloud.r-project.org/web/packages/RcppCCTZ/index.html) meaning we will have CCTZ access from R on all platforms supported by R.  

We're going to see how it does in terms of builds and tests.  But should everything pan out as we anticipate, it should provide broader coverage for CCTZ builds -- and we'd be happy to send it over here as a PR if you think that it adds value.  Otherwise we'd be equally happy to keep it locally in our package.

**Comment by devbww** [comment]
It sounds like there is nothing more to consider here, so closing.
