### ISSUE TITLE
sys_seconds is a duration in cctz, but a time_point in C++20

### ISSUE THREAD

**Issue by tudor** [google/cctz#78]
https://en.cppreference.com/w/cpp/chrono/system_clock shows that C++20 has adopted `sys_seconds` as:

```
template<class Duration>
using sys_time = std::chrono::time_point<std::chrono::system_clock, Duration>; 
using sys_seconds = sys_time<std::chrono::seconds>;
```

whereas cctz defines it as

```
using sys_seconds = std::chrono::duration<std::int_fast64_t>;
```

Yes, they are in different namespaces, but it would be great if the two were unified, especially if you aim to have cctz adopted as part of the C++ standard.

**Comment by devbww** [comment]
Hi Tudor,

Thanks for the heads-up.

While std::chrono::sys_seconds is a time_point and cctz::sys_seconds a duration (which means the chances for confusion are even less), I think if I were to make the choice again I would indeed make cctz::sys_seconds be just cctz::seconds (it more closely resembles std::chrono::seconds).

Getting rid of cctz::sys_seconds altogether is problematic though due to existing users.  I'll work on something to at least deprecate it.

As for standardization, while one of the initial goals of cctz was to suggest an alternative (and IOHO better) treatment of time zones and civil time than what was being proposed, it seems like that ship has sailed.  So the best we can do now is continue to provide the cctz library and let users vote with their feet.

Bradley

**Comment by devbww** [comment]
Done.  We now use cctz::seconds, and cctz::sys_seconds is a deprecated alias.  Thanks.
